### ISSUE TITLE
Full design details

### ISSUE THREAD

**Issue by azubieta** [plasma-extensions/plasma-widget-bladerunner#4]
@UriHerrera Need as usual all the details of the design (colors, paddings, etc).

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/WAGnVfM.png)
![](http://i.imgur.com/MUlyr4J.png)
![](http://i.imgur.com/GImFuIp.png)

The Calculator and Bookrmark runner use the padding of the Places runner.

The bottom line of the tabs when selected is 2px, when it's not selected is 1px.
