### ISSUE TITLE
Setions contents

### ISSUE THREAD

**Issue by azubieta** [plasma-extensions/plasma-widget-bladerunner#5]
@UriHerrera @star-buck 
All the functional parts are finished now it's required to specify which "runners" will be include in each section. You can see the list of available runners in the krunner settings.

**Comment by UriHerrera** [comment]
As in the mockup: https://github.com/plasma-light/plasma-widget-krunner/issues/1

The runners would be:

Display the search history (though this is not a runner it appears when you click in the text field and press down).
- Applications
- Places (Ubicaciones)
- Calculator
- Bookmarks

**Comment by azubieta** [comment]
Ok, so it's only missing the first. I'll get on it.

**Comment by azubieta** [comment]
Done.
